parameters:
    widop_google_analytics.class: Widop\GoogleAnalytics\Service
    widop_google_analytics.client.class: Widop\GoogleAnalytics\Client
    widop_google_analytics.query.class: Widop\GoogleAnalytics\Query

services:
    widop_google_analytics:
        class: '%widop_google_analytics.class%'
        arguments:
            - '@widop_google_analytics.client'

    widop_google_analytics.client:
        class: '%widop_google_analytics.client.class%'

    widop_google_analytics.query:
        class: '%widop_google_analytics.query.class%'
