services:
    widop_google_analytics:
        class: Widop\GoogleAnalytics\Service
        arguments:
            - '@widop_google_analytics.client'

    widop_google_analytics.client:
        class: Widop\GoogleAnalytics\Client
        arguments:
            - '%widop_google_analytics.client_id%'
            - '%widop_google_analytics.private_key%'
            - ~ #httpclient
            - '%widop_google_analytics.service_url%'
            - ~ #cache

    widop_google_analytics.query:
        class: Widop\GoogleAnalytics\Query
        arguments:
            - '%widop_google_analytics.profile_id%'
